### ISSUE TITLE
How to access LQIP value of an image?

### ISSUE THREAD

**Issue by kaanbasal** [saiichihashimoto/sanity-typed-schema-builder#168]
As per sanity [documentation](https://www.sanity.io/docs/image-metadata) there is an image metadata configuration. is there any way to get these values using the library?

Thanks

**Comment by saiichihashimoto** [comment]
It's not typed in this library. It can be though, PRs are welcome! Using it untyped in your own application is also an option, considering it doesn't change the type of anything returned in the application.

**Comment by kaanbasal** [comment]
thank you! if I find the time, I will try my best to create a PR definitely.
