### ISSUE TITLE
How do we add validation?

### ISSUE THREAD

**Issue by bawahakim** [saiichihashimoto/sanity-typed-schema-builder#169]
Hello,

I am unsure if I may be missing something, but it seems the `validation` property is not a valid type. I see we can use `Zod`, but that seems to apply only for transformation, not validation.

Is there a way to use validation?

Thanks

**Comment by saiichihashimoto** [comment]
You should be able to do validations. Can you give a code example of what is not working for you?

**Comment by saiichihashimoto** [comment]
I'm double checking, and `validation` is definitely a valid type still, so I'm not certain what's going on. `validation: (Rule) => Rule.custom(...)` is completely available. I'm going to close this for now, hopefully you've solved your issue or you can come up with a good example of your issue.
