### ISSUE TITLE
Migrate to sanity v3

### ISSUE THREAD

**Issue by saiichihashimoto** [saiichihashimoto/sanity-typed-schema-builder#171]
Mainly, migrating `@sanity/types` to `3.x.x`

**Comment by mckelveygreg** [comment]
With v3's `defineType`, `defineField`, and `defineArrayMember`, will we be able to use those built in sanity functions, but perhaps use this library to extract the resolved types that would be ready for exporting?

**Comment by saiichihashimoto** [comment]
@miklschmidt I have no idea, I don't know what those are. From what I gather, they give typescript hints to define schemas. Theoretically, it narrows the types to derive the types directly from the schemas. If so, great news! We can easily make a library that derives types from a `defineType` type and deprecate this library. That would be amazing, I would love to get as close to using the native schemas as possible.

Aside from that, this task is mostly to make sure this library as-is works with `@sanity/types: "^3.0.0"`.

**Comment by mckelveygreg** [comment]
Lolz, I think you got me mixed up again, regardless thanks for the update!

I'm not sure how to derive the types myself, so I have some learning to do then!

**Comment by saiichihashimoto** [comment]
Lol yes I did. Sorry to both of you for that!

**Comment by saiichihashimoto** [comment]
And if you find a way to derive the types yourself, *please* make that a package. I'd love to make it, but I'm doing this whenever I happen to have time (rarely) and the amount of people who would want it is probably... everyone.
