### ISSUE TITLE
Make package.json engines.node less strict

### ISSUE THREAD

**Issue by drwpwrs** [saiichihashimoto/sanity-typed-schema-builder#191]
Installing this package as a dependency with yarn throws an incompatible engine error if you're not running the specific version of node from `package.json`'s `engines.node` (currently `18.12.1`).

The error can be ignored successfully with yarn's `--ignore-engines`, but I am wondering if it's preferable to loosen the match to something like `^18.12.1`. 

Let me know if I'm missing something, otherwise I would be happy to open a PR.

**Comment by saiichihashimoto** [comment]
In general I like exact versions across the board, but I think this makes sense with a `^`. Open that PR! Thanks!
