### ISSUE TITLE
How do I use the prepare function for preview?

### ISSUE THREAD

**Issue by MrNekoShin** [saiichihashimoto/sanity-typed-schema-builder#203]
I can't seem to find the proper syntax for the prepare function

**Comment by saiichihashimoto** [comment]
I don't really understand. It should work just as it does with a sanity schema does natively. If it helps, here's a test that shows that: https://github.com/saiichihashimoto/sanity-typed-schema-builder/blob/ffdbab6dae5f280f79c3a1d472e6cf4af67218f7/src/document/index.spec.ts#L323

**Comment by saiichihashimoto** [comment]
@MrNekoShin please comment/make a new comment if you've got a response but otherwise, I'm going to close this.
