### ISSUE TITLE
Possible to parse Picked/omitted data?

### ISSUE THREAD

**Issue by schietegal** [saiichihashimoto/sanity-typed-schema-builder#211]
Hey,

i'm fetching some data, but do not need all that are defined in sanity

Let's say i have the following :
```typescript
type Referenzen = Pick<s.infer<typeof referenzen>, 'name' | 'link' | 'logo'>;
   
const data: Referenzen[] = await sanity_client.fetch(`* [_type == "referenzen"]{
			name,
			link,
			logo 
		}`);
```

I want to parse the received data, but with the given method it isn't successful (obviously)
```typescript
const current_parsed_data = referenzen.parse(data) //ZodError
```

Is there a way to partial parse the data? Something like:
```typescript
const wanted_parsed_data = referenzen.parse(data, { pick: { name: true, link: true, logo: true } });
// or
const wanted_parsed_data2 = referenzen.zodObject.pick({ name: true });
```

Thank you for your work!

Edit: relates to  #210 bc of ZodObject, sorry 🤖

**Comment by saiichihashimoto** [comment]
Yeah, this should be solved by #210. I think ZodObject will let you pick a partial off of it.
